### ISSUE TITLE
Verhalten wenn CAS nicht erreichbar ist

### ISSUE THREAD

**Issue by janiak-minova** [minova-afis/aero.minova.rcp#440]
Wenn das CAS nicht erreichbar ist, soll den Nutzern immer eine entsprechende Fehlermeldungen geworfen werden.
- [x] Dies soll als Popup-Fenster geschehen.
- [x] Es wird ein Default Timeout von 15s eingeführt, der in den Einstellungen angepasst werden kann.

Zusätzlich soll sich die Anwendung wie folgt verhalten, je nachdem, wann das CAS nicht erreichbar ist:
- [x] Beim Starten der Anwendung - Kein Default-Profil: Die Login-Maske bleibt geöffnet (siehe auch #63). 
- [x] Beim Starten der Anwendung - Default-Profil: Profil (mit evtl. veralteten Masken) laden. Die Timeout-Zeit beim Start kann nicht über die Einstellungen verändert werden.
- [x] Laden des Indexes: Vorheriger Zustand des Indexes bleibt bestehen, Ladeknopf kann wieder aktiviert werden (siehe auch #468)
- [x] Anfrage einer Lookup-Tabelle: Wenn vorhanden Nutzen des Caches, mit entsprechender Warnung an Nutzer
- [x] Beim Speichern/Ändern/Löschen eines Eintrages über das Detail: Die eingetragenen Werte im Detail bleiben stehen
- [x] Anfragen einer Datei/ des Hashes einer Datei: Wenn möglich vorhandene Dateien nutzen
- [x] Auflösen eines Tickets (SIS): Die Messages in den Feldern werden zurückgesetzt (siehe auch #438)
- [x] Bei Anfrage von PDF-Dateien wird der Timeout auf 30s erhöht
