### ISSUE TITLE
Release 12.0.16 unter MacOS

### ISSUE THREAD

**Issue by janiak-minova** [minova-afis/aero.minova.rcp#505]
Getestet mit Server http://publictest.minova.com:17280/cas

# Testprotokoll unter macOS

## Anmeldung
- [x]  Anmeldung an den Server mittles Default - Profil
- [x] Anmeldung an den Server durch manuelles eintragen der Anmeldedaten
- [x] Wiederholtes Anmelden mit einem Profil, bei dem das Passwort einmal falsch eingetragen wurde (siehe 1. Kommentar #388)
- [x] Wiederholtes Anmelden mit einem Profil, bei dem das Passwort falsch eingetragen wurde und die Anwendung direkt darauf geschlossen wurde (siehe 2. Kommentar #388)

### Eingetragene Suchkriterien werden geladen (DEFAULT).
- [x] Funktioniert

## Indexdruck
<img width="823" alt="Bildschirmfoto 2021-04-20 um 22 27 50" src="https://user-images.githubusercontent.com/77741125/115459729-acb68880-a227-11eb-9ce3-49d04540c6d9.png">

- [x] Alle Spalten haben die selbe Reihenfolge wie auch in der Anwendung angezeigt (Reihenfolge kann verändert werden)

### Druckeinstellungen
- [x] XML/XSL können erstellt werden (Workspaceordner -> PDF)
- [x] Schriftgröße kann verändert werden
- [x] Spaltenbreite kann optimiert werden, ansonsten wird Breite aus Index übernommen
- [x] Leere Spalten können verborgen werden
- [x] Gruppenspalten können verborgen werden
- [x] Suchkriterien können angezeigt werden 
- [x] Interne Vorschau kann aktiviert werden 

## Traverselistener
- [x] Tab selektiert das nächste Feld (Wenn SelectAllControls **nicht** gesetzt ist)
- [x] Tab selektiert alle Controls (Toolbar, Section usw.) (Wenn SelectAllControls gesetzt ist)
- [x] Enter selektiert das **nächste leere** Pflichtfeld (Wenn EnterSelectsFirstRequired **nicht** gesetzt ist)
- [x] Enter selektiert das **erste leere** Pflichtfeld (Wenn EnterSelectsFirstRequired gesetzt ist)
- [x] Bei Enter in einer Auswahlbox bleibt man im **selben** Feld (Wenn LookupEnterSelectsNextRequired **nicht** gesetzt ist)
- [x] Enter in einer Auswahlbox selektiert das **nächste leere**  Pflichtfeld (Wenn LookupEnterSelectsNextRequired gesetzt ist, EnterSelectsFirstRequired ist egal)

## PerspectiveSwitcher
- [x] Die Perspektive kann über das Menü oben geändert werden
- [x] Die Perspektive kann über die Leiste unten geändert werden
- [x] Bei einem Neustart sind in der Leiste die gleichen Perspektiven wieder vorhanden
- [ ] Perspektiven können über Rechtsklick geschlossen werden (inklusive der letzten)
- [x] Es wird unterstützt, dass Masken in der application.mdi unterschiedliche Dateinamen und IDs haben (siehe #487)

# Tests für CTS VG Eibelstadt
 
## Maske Anruf
<img width="706" alt="Bildschirmfoto 2021-04-20 um 22 29 07" src="https://user-images.githubusercontent.com/77741125/115459886-da9bcd00-a227-11eb-806c-a44b78983c75.png">

- [x] Erfassung eines Anrufs mittels Eingabe einer neuen Testperson
- [x] Erfassung eines Anrufs mittels bereits existierender Testperson
- [x] Gleichzeitiges erfassen von Terminen, wenn es 2 Slots gibt (Keiner vorher belegt)
- [x] Gleichzeitiges erfassen von Terminen, wenn es 2 Slots gibt (Einer vorher belegt) -> Einer funktioniert, eine Fehlermeldung

<img width="574" alt="Bildschirmfoto 2021-04-20 um 22 35 35" src="https://user-images.githubusercontent.com/77741125/115460655-cf956c80-a228-11eb-8342-5fb660745e56.png">

- [x] Testtermin der einer Person zugeordnet wurde, darf keiner anderen Person zugeordnet werden (überschreiben) 
(Zuordnung nehmen, und einer anderen Person zuordnen (Lookup))
- [x]  Daten einer zugeordneten Testperson sollen geändert werden.  Zugeordneter Termin bleibt bestehen
(Die Angaben der Testperson werden aktualisiert, aber der Termin bleibt bestehen)

## Maske Testperson
- [x] Passwort wird nicht im Klartext angezeigt
- [x] Passwort der Testperson kann nicht geändert werden
- [x] Passwort der Testperson kann zurückgesetzt werden

## Maske Anmeldung
<img width="679" alt="Bildschirmfoto 2021-04-20 um 22 33 37" src="https://user-images.githubusercontent.com/77741125/115460366-7a595b00-a228-11eb-92df-a0ad2f97355f.png">

### E-Mail Versand 
- [x] positives Testergebnis
- [x] negatives Testergebnis

### Detaildruck (Maske Anmeldung)
- [x] Funktioniert mit positiv
- [x] Funktioniert mit negativ

**Comment by weber-minova** [comment]
wie in #502 beschrieben lässt sich nur die letzte Maske nicht schließen, ansonsten passt alles
