### ISSUE TITLE
Beschreibung / Dokumentation für das Erstellen eines PlugIns.

### ISSUE THREAD

**Issue by CE7** [minova-afis/aero.minova.rcp#803]
Link zur [Doku](https://github.com/minova-afis/aero.minova.rcp/blob/master/PluginErstellen.adoc)

Erstellen des Plugins:
- [x] Eigenes Repository pro Plugin? 
- [x] Plugin erstellen
- [x] Targetplatform (inkl. Core-Anwendung von Updatesite)
- [x] Anpassen von .poms und .mvn
- [x] Bauen/Taggen/Releasen der Anwendung (per Hand oder automatisch auf git -> github workflow)
- [x] Erstellen eines Test-Plugins, sodass beim Bauen die Tests automatisch laufen (In pom als Modul eintragen) #822
- [x] Einrichtung im CAS

Funtionalitäten der Helper:
- [x] Zugriff auf Felder einer Maske
- [x] Reagieren auf User-Actions
- [x] Belegen von Werten inkl. Dirty-Flag. Es gibt eine Tabelle die wir aktuell als Dummy verwenden. (Vorbelegte Werte). Damit entscheiden wir ob eine Änderung von Werten stattgefunden hat.  
- [x] Felder readonly/required #840
- [X] Sections ein-/ausblenden (Angabe in der Maske) #839
- [x] Buttons de-/aktivieren #838 
- [x] Anwendungsspezifische Einstellungen  #808
- [x] param-string Felder -> Setzen der Felder #755
- [x] Ersetzen von `tools.getSQLValue()` in der Maske
- [x] Vorschlagsliste von Lookup-Feldern filtern
- [x] Benachrichtigen der Nutzer (über Notification oder Fehlermeldung)
- [x] Ausführen von Handlern (z.B. zum Speichern/neues Detail/Index laden/.....)
- [x] Hinzufügen neuer Einstellungen

Tipps zum Progammieren:
- [x] Plugin Testen/Entwickeln, ohne gebaute Version auf Server bereitstellen zu müssen (Im MinovaPluginService DEBUG = true, Plugin in Debug Config aufnehmen)
- [x] "Plugins aus Entwicklungsumgebung nutzen" aktualisieren

**Comment by janiak-minova** [comment]
Die Doku findet sich [hier](https://github.com/minova-afis/aero.minova.rcp/blob/master/PluginErstellen.adoc).

**Comment by janiak-minova** [comment]
Die Doku ist soweit erstellt. Weitere Dokumentations wird hinzugefügt, sobald neue Funktionalitäten implementiert werden.
